### ISSUE TITLE
Tests fail for cocoapods-core 1.0.0

### ISSUE THREAD

**Issue by rmetzler** [versioneye/versioneye-core#17]
Updating cocoapods in `Gemfile`
```ruby
gem 'cocoapods-core'     , '1.0.0'
```

and running some tests results in failing tests:
```
$ rspec spec/versioneye/parsers/podfile*
W, [2016-05-20T07:26:31.947569 #67323]  WARN -- : Creating scope :parents. Overwriting existing method Project.parents.
initialize Settings
load config/settings.json
start initialize versioneye-core
 - initialize Etcd!
load config/settings.json
 - initialize Logger
"initialize"
 - initialize MongoDB for test. DB_PORT_27017_TCP_ADDR: localhost:27017.
 - reload Settings from DB!
 - initialize ElasticSearch with localhost:9200 for env: test
 - initialize init_memcached!
 - initialize email settings
 - initialize Stripe
 - initialize Amazon S3
end initialize versioneye-core
..FFFF."load Lockfile from_url https://raw.githubusercontent.com/DenisDbv/OpenAuth/master/Podfile.lock"
...

Failures:

  1) PodfileParser.parse_file should read a simple podfile and return project, dependencies
     Failure/Error: project.should be_truthy

       expected: truthy value
            got: nil
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:67:in `parse_and_check'
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:91:in `block (3 levels) in <top (required)>'

  2) PodfileParser.parse_file should parse a podfile with target definitions
     Failure/Error: project.should be_truthy

       expected: truthy value
            got: nil
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:67:in `parse_and_check'
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:134:in `block (3 levels) in <top (required)>'

  3) PodfileParser.parse_file should parse a podfile with target definitions
     Failure/Error: project.should be_truthy

       expected: truthy value
            got: nil
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:67:in `parse_and_check'
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:173:in `block (3 levels) in <top (required)>'

  4) PodfileParser.parse_file should parse simple targets in podfile
     Failure/Error: project.should be_truthy

       expected: truthy value
            got: nil
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:67:in `parse_and_check'
     # ./spec/versioneye/parsers/podfile_parser_spec.rb:210:in `block (3 levels) in <top (required)>'

1 deprecation warning total

Finished in 2.4 seconds (files took 2.55 seconds to load)
10 examples, 4 failures

Failed examples:

rspec ./spec/versioneye/parsers/podfile_parser_spec.rb:89 # PodfileParser.parse_file should read a simple podfile and return project, dependencies
rspec ./spec/versioneye/parsers/podfile_parser_spec.rb:122 # PodfileParser.parse_file should parse a podfile with target definitions
rspec ./spec/versioneye/parsers/podfile_parser_spec.rb:161 # PodfileParser.parse_file should parse a podfile with target definitions
rspec ./spec/versioneye/parsers/podfile_parser_spec.rb:203 # PodfileParser.parse_file should parse simple targets in podfile
```

Also there is this warning:
```
Deprecation Warnings:

Using `should_not` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/richardmetzler/Code/versioneye-core/spec/versioneye/parsers/podfile_parser_spec.rb:11:in `block (3 levels) in <top (required)>'.


If you need more of the backtrace for any of these deprecations to
identify where to make the necessary changes, you can configure
`config.raise_errors_for_deprecations!`, and it will turn the
deprecation warnings into errors, giving you the full backtrace.
```

**Comment by rmetzler** [comment]
Differences between `cococapods-core` `0.39` and `1.0`: https://github.com/CocoaPods/Core/compare/0.39-stable...1-0-stable

**Comment by reiz** [comment]
Thanks for opening this ticket. The warning can be solved easily. The major update to cocoapods-core 1.0.0 is the bigger issue. In the release notes here they mention breaking changes: https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#100beta1-2015-12-30.

**Comment by reiz** [comment]
@rmetzler I just fixed the warnings and added a new script to run the podfile tests only.
