### ISSUE TITLE
when starting first time, then `log/tasks_development.log` is missing

### ISSUE THREAD

**Issue by timgluz** [versioneye/versioneye-core#18]
I started `rake console` and typed `VersioneyeCore.new`, then logger throwed exception:

```
Errno::ENOENT: No such file or directory @ rb_sysopen - log/tasks_development.log
	from /Users/timgluz/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:37:in `initialize'
	from /Users/timgluz/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:37:in `open'
	from /Users/timgluz/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/open-uri.rb:37:in `open'
	from /Users/timgluz/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:711:in `create_logfile'
	from /Users/timgluz/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/logger.rb:705:in `rescue in open_logfile'
```

**Comment by reiz** [comment]
The problem was that the `log` directory was missing. It's fixed now.
