### ISSUE TITLE
Nuget Parser is throwing nil pointer exception

### ISSUE THREAD

**Issue by reiz** [versioneye/versioneye-core#31]
It seem that the nuget parser has a small bug. Getting this error on production: 

```
2016-07-25 08:34:44.738 [wtf] ERROR in parse_content({
  "version": "1.0.0-*",
  "dependencies": {
    "Microsoft.CodeAnalysis.CSharp.Workspaces": "1.0.0",
    "Microsoft.Composition": "1.0.30",
    "Microsoft.Dnx.Runtime": "1.0.0-rc1-final",
    "Microsoft.Dnx.Compilation": "1.0.0-rc1-final",
    "Microsoft.Dnx.Compilation.CSharp": "1.0.0-rc1-final",
    "Microsoft.Dnx.Compilation.CSharp.Common": "1.0.0-rc1-final"
  },
  "frameworks": {
    "dnx451": {
      "frameworkAssemblies": {
        "System.Globalization": ""
      }
    },
    "dnxcore50": {
      "dependencies": {}
    }
  }
}) -> undefined method `version' for nil:NilClass (pid:57)
2016-07-25 08:34:44.738 [wtf] /usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_parser.rb:119:in `parse_version_data'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_parser.rb:75:in `parse_requested_version'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_parser.rb:217:in `parse_dependency_version'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_parser.rb:203:in `block in parse_dependency_versions'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_parser.rb:203:in `each'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_parser.rb:203:in `parse_dependency_versions'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/parsers/nuget_json_parser.rb:19:in `parse_content'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/services/project_parse_service.rb:23:in `parse_content'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/services/project_import_service.rb:103:in `create_project_from'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/services/project_import_service.rb:51:in `import_from_github'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/workers/git_repo_file_import_worker.rb:57:in `import'
/usr/local/bundle/bundler/gems/versioneye-core-7ae762b1d139/lib/versioneye/workers/git_repo_file_import_worker.rb:20:in `block in work'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/consumer.rb:56:in `call'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/channel.rb:1703:in `block in handle_frameset'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/consumer_work_pool.rb:97:in `block (2 levels) in run_loop'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/consumer_work_pool.rb:92:in `loop'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/consumer_work_pool.rb:92:in `block in run_loop'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/consumer_work_pool.rb:91:in `catch'
/usr/local/bundle/gems/bunny-2.4.0/lib/bunny/consumer_work_pool.rb:91:in `run_loop' (pid:57)
```

**Comment by reiz** [comment]
OK. This is fixed. Many Thanks.
